name: Gilden-Plugin
main: de.Initium.Gilden.Main.Main
version: 0.1-SNAP
api-version: 1.16
authors:
  - doppelkool
  - Modstrype
depends:
  - Citizens
  - Vault
  - GemsEconomy
  - PlayerLogger
  - Insel
website: https://initium-novum.net/
commands:
  gilde:
    usage: /<command>
    description: Main Command to the plugin
  gctest:
    usage: /<command>
    description: Test-Gilde-Chat-CMD
  confirm:
    description: Plugin-Extension
  deny:
    description: Plugin-Extension